/**
 * Generates the practice bank as `supabase/seed.sql`.
 *
 *   pnpm --filter @nonet/engine seed-bank [count-per-difficulty]
 *
 * Seeds are `1..count` within each band, so the bank is reproducible: the file
 * is checked in, but it can be regenerated byte-identically from this script,
 * and any single puzzle can be rebuilt from its band and seed alone. That is
 * the same guarantee the daily has, for the same reason (NONET-9).
 *
 * Practice seeds and daily seeds cannot collide in a way that matters: daily
 * seeds are 32-bit hashes and practice seeds are small integers, and the unique
 * index is on `(kind, difficulty, seed)`, so the two spaces are separate rows
 * regardless.
 */
import { writeFileSync } from 'node:fs';
import { DIFFICULTIES } from '../src/types.ts';
import { formatGrid } from '../src/grid.ts';
import { generatePuzzle } from '../src/generate.ts';

const PER_DIFFICULTY = Number(process.argv[2] ?? 1000);
const OUT = new URL('../../../supabase/seed.sql', import.meta.url);

function row(difficulty: string, seed: number): string {
  const puzzle = generatePuzzle(difficulty as (typeof DIFFICULTIES)[number], seed);
  // Zeros, not dots: the column is constrained to digits.
  return `('practice', '${difficulty}', '${formatGrid(puzzle.givens, '0')}', '${formatGrid(
    puzzle.solution,
    '0',
  )}', ${puzzle.score}, ${seed})`;
}

const started = Date.now();
const rows: string[] = [];

for (const difficulty of DIFFICULTIES) {
  const at = Date.now();
  for (let seed = 1; seed <= PER_DIFFICULTY; seed += 1) {
    rows.push(row(difficulty, seed));
  }
  process.stdout.write(
    `${difficulty.padEnd(7)} ${PER_DIFFICULTY} puzzles in ${((Date.now() - at) / 1000).toFixed(1)}s\n`,
  );
}

const sql = [
  '-- The practice bank. Generated by `pnpm --filter @nonet/engine seed-bank`.',
  '--',
  '-- Reproducible: every row is `generatePuzzle(difficulty, seed)` with seeds',
  '-- 1..N per band, so this file can be rebuilt byte-identically and any single',
  '-- puzzle can be regenerated from the two columns that identify it.',
  '--',
  '-- `on conflict do nothing` against the (kind, difficulty, seed) index, so',
  '-- loading it twice is a no-op and growing the bank later only adds rows.',
  '',
  'insert into public.puzzles (kind, difficulty, givens, solution, score, seed) values',
  `${rows.join(',\n')}`,
  'on conflict (kind, difficulty, seed) do nothing;',
  '',
].join('\n');

writeFileSync(OUT, sql, 'utf8');

process.stdout.write(
  `\n${rows.length} puzzles, ${(sql.length / 1024 / 1024).toFixed(2)} MB, ` +
    `${((Date.now() - started) / 1000).toFixed(1)}s total\n`,
);
